CREATE DATABASE DEMO_DB;

USE DEMO_DB;

CREATE TABLE STUDENTS(
STUDENT_ID INT,
NAME varchar(50),
AGE INT,
COURSE VARCHAR (50)
);

SELECT * FROM STUDENTS;

INSERT INTO STUDENTS VALUES (1,"SHUBH",20,"DATA ANALYST");


CREATE TABLE EMPLOYEE (
EMP_iD INT,
EMP_NAME VARCHAR (50),
SALARY INT,
DEPARTMENT VARCHAR(50)
);

SELECT * FROM EMPLOYEE;


INSERT INTO EMPLOYEE VALUES(102,"SHUBHH",7500,"DATA ANALYST"), (108,"HARSH",9000,"DATA ANALYST");



CREATE TABLE PRODUCT (
PRODUCT_ID INT,
PRODUCT_NAME VARCHAR(50),
PRICE_QUANTITY INT
);

SELECT * FROM PRODUCT;

CREATE TABLE BOOKS (
BOOK_ID INT,
TITLE VARCHAR (100),
AUTHOR VARCHAR (100),
PRICE INT
);

SELECT * FROM BOOKS;

CREATE TABLE CUSTOMERS (
CUSTOMER_ID INT,
CUSTOMER_NAME VARCHAR(50),
CITY VARCHAR (100),
PHONE_NUMBER VARCHAR (12)
);

SELECT * FROM CUSTOMERS;